[build]
command = "git submodule update --init --remote && bundle exec jekyll build --config '_config.yml,_config_staging.yml'"
publish = "_site"
environment = { RUBY_VERSION = "2.6.2" }

[[redirects]]
  from = "/"
  to = "/courses/list"

[dev]
# NB on win64 (cmd or bash shells) --live reload is broken - s/-w --livereload/--no-watch
command = "bundle exec jekyll serve -w --livereload --trace --config _config.yml,_config_staging.yml"

[functions]
directory = "_functions"
node_bundler = "esbuild"

[[plugins]]
package = "@netlify/plugin-functions-install-core"
